trigger:
  branches:
    include:
      - master
      - test

variables:
  JIT_API_KEY: $(JitApiKey)  # Jit.io API anahtarını buraya gizli değişken olarak tanımlayın

pool: TolgaLocal

steps:
- script: echo Hello, world!
  displayName: 'hello'

- script: |
    echo "Jit.io taraması başlatılıyor..."
    curl -X POST -H "Authorization: Bearer $JIT_API_KEY" -H "Content-Type: application/json" -d "{\"project\": \"json-server\", \"repo\": \"than57\", \"branch\": \"master\"}" "https://api.jit.io/scan"
  displayName: 'Jit.io Taramasını Başlat'

- script: |
    echo "Jit.io taraması sonuçları alınıyor..."
    curl -X GET -H "Authorization: Bearer $JIT_API_KEY" "https://api.jit.io/results?project=json-server&repo=than57&branch=master"
  displayName: 'Jit.io Tarama Sonuçlarını Al'