applications:
- api_domain: api.appliaction.com
  application_name: exam-api
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: .jit/swagger.yaml
  type: api
github_branch_protection:
  organization:
    amount_of_required_reviews: 1
    required_status_checks:
    - ONAY
